spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgresql
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    
jwt:
  secret: MinhaChaveSecretaJWT12345678901234567890
  expiration: 86400000  # 1 dia em milissegundos
  

  
  

